language: node_js
node_js:
  - "12.16.1"
dist: trusty
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- npm run test-headless
- ng build --prod --base-href https://Lando92.github.io/gateway-app/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/gateway-app
  on:
    branch: master
